#!/usr/bin/env sh

# Ensure the user is running with superuser privileges
[ $(id -u) != 0 ] && echo 'This script must be run with superuser privileges.' && exit 0

IPCIDR="([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}/[[:digit:]]{1,2}"
# TODO: Ensure /etc/netplan is the correct dir for configs
configfile=$(ls /etc/netplan/01-*.yaml)
# Ensure there is a backup. Requires sudo privileges
#[ ! -e $configfile.bak ] && backuprestore backup $configfile
[ ! -e $configfile.bak ] && cp $configfile $configfile.bak
hostname=$(cat /etc/hostname)

getconnectedinterfaces(){
    interfaces=$(ls /sys/class/net)
}

selectinterface(){
    [ -z $interfaces ] && getconnectedinterfaces
    echo 'AVAILABLE INTERFACES:'
    echo "$interfaces"
    read -p 'What interface do you want to configure? ' interface
    [ $(echo $interface | grep -e "$interfaces") ] || selectinterface
}

getinterfaceinformation(){
    [ -z $interface ] && selectinterface
    renderer=$(grep renderer $configfile | awk '{print $2}')
    dhcp4=$(grep dhcp4 $configfile | awk '{print $2}')
    [ ! $dhcp4 ] && dhcp4='no'
    ipv4=$(ip address show dev $interface | grep -e 'inet ' | sed -E 's|[^[:digit:]]*(([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}/[[:digit:]]{1,2}).*|\1|')
    gateway4=$(ip route show dev $interface | grep -e 'default via' | sed -E 's/[^[:digit:]]*(([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}).*/\1/' | head -1)
    nameserver4=$(grep -e 'nameserver' /etc/resolv.conf | cut -f2 -d' ')
    domainname=$(egrep -e "^([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}[^[:alpha:]]*$hostname\.?([[:alpha:]])?" /etc/hosts | cut -f5 -d. | awk '{print $2}')
    [ ! $domainname ] && domainname='not set'
}

printinterfaceinformation(){
    [ $1 ] && interface=$1 && getinterfaceinformation $interface
    [ -z $renderer $dhcp4 $ipv4 $gateway4 $nameserver $domainname ] 2>/dev/null && getinterfaceinformation
    echo "Renderer: $renderer"
    echo "DHCP: $dhcp4"
    echo "IP: $ipv4"
    echo "gateway: $gateway4"
    echo "nameservers: $nameserver"
    echo "domain: $domainname"
}

getconfigvalue(){
    [ $2 ]  && file=$2 || file=$configfile.edit
    egrep -e "^[[:blank:]]*$1:" $file
}

backuprestore(){
    [ $2 ] && file=$2 || read -p 'Enter file: ' file
    [ ! -f $file ] && backuprestore $1
    backup(){
        cp $file "$file.bak"
    }
    restore(){
        cp "$file.bak" $file
    }
    case $1 in
        backup) backup $2;;
        restore) restore $2;;
        *) echo "backup\nrestore";;
    esac
}

prepareconfigfile(){
    [ -z $interface ] && selectinterface
    cp $configfile.bak $configfile.edit
    #header=$(egrep -e '^#' $configfile)
    printf "$header\nnetwork:\n    version:$(getconfigvalue version | cut -f2 -d:)\n    renderer:$(getconfigvalue renderer | cut -f2 -d:)\n    ethernets:\n         $interface:\n            dhcp4:$(getconfigvalue dhcp4 | cut -f2 -d:)\n            addresses:$(getconfigvalue addresses | head -1 | cut -f2 -d:)\n            gateway4:$(getconfigvalue gateway | cut -f2 -d:)\n            nameservers:\n                addresses:$(getconfigvalue addresses | tail -1 | cut -f2 -d:)\n" > $configfile.edit
    [ -z $renderer $dhcp4 $ipv4 $gateway4 $nameserver $domainname ] 2>/dev/null && getinterfaceinformation $interface
    changeconfigfile renderer $renderer
    changeconfigfile dhcp4 $dhcp4
    changeconfigfile ipv4 $ipv4
    changeconfigfile gateway4 $gateway4
    changeconfigfile nameserver4 $nameserver4
}

changeconfigfile(){
    [ ! -f "$configfile.edit" ] && prepareconfigfile
    renderer(){
        if [ $1 ]; then
            renderer=$1
        else
            read -p 'Manage interfaces with either: 1) networkd or 2) NetworkManager [1,2] ' renderer
            [ "$renderer" = '2' -o "$renderer" = 'NetworkManager' ] && renderer='NetworkManager' || renderer='networkd'
        fi
        sed -Ei "/$(getconfigvalue renderer)/s/:(.*)?$/: $renderer/" $configfile.edit
    }
    dhcp4(){
        if [ $1 ]; then
            dhcp4=$1
        else
            read -p 'Manage interface via DHCP? [y/N] ' dhcp4
        fi
        sed -Ei "/$(getconfigvalue dhcp4)/s/:(.*)?$/: $dhcp4/" $configfile.edit
    }
    ipv4(){
        if [ $1 ]; then
            ipv4=$1
        else
            read -p 'Please enter a valid IPv4 address for address: ' ipv4
            read -p 'Please enter a valid CIDR address for subnet: ' cidr
            [ $(echo "$ipv4/$cidr" | egrep -e '([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}/[[:digit:]]{1,2}') ] && ipv4="$ipv4/$cidr" || changeconfigfile ipv4
        fi
        tmp=$ipv4
        ipv4=$(echo $tmp | sed 's|/| |')
        sed -Ei "1,/addresses/s/(addresses:)(.*)?$/\1 \[$ipv4\]/" $configfile.edit
        ipv4=$tmp
        sed -Ei "s/(([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}) ([[:digit:]]{1,2})/\1\/\3/" $configfile.edit
    }
    gateway4(){
        if [ $1 ]; then
            gateway4=$1
        else
            read -p 'Please enter a valid IPv4 address for gateway: ' gateway4
            [ $(echo "$gateway4" | egrep -e '([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}') ] || changeconfigfile gateway4
        fi
        sed -Ei "/$(getconfigvalue gateway4)/s/:(.*)?$/: $gateway4/" $configfile.edit
    }
    nameserver4(){
        if [ $1 ]; then
            nameserver4=$1
        else
            read -p 'Please enter a valid IPv4 address for nameserver. You can enter two entries by separating entries with a comma (e.g. ?.?.?.?,?.?.?.?) ' nameserver4
            [ $(echo "$nameserver4" | egrep -e '(([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3},?){1,2}') ] || changeconfigfile nameserver4
        fi
        sed -Ei "$ s|(addresses:)(.*)?$|\1 [$nameserver4]|" $configfile.edit
        #sed -Ei "s/(DNS=)/\1$namderver4/" /etc/systemd/resolved.conf
    }

    case $1 in
        renderer) renderer $2;;
        dhcp4) dhcp4 $2;;
        ipv4) ipv4 $2;;
        gateway4) gateway4 $2;;
        nameserver4) nameserver4 $2;;
        *) echo "renderer,dhcp4,ipv4,gateway4,nameserver4";;
    esac
}

verifyconfig(){
    cp $configfile.edit $configfile
    netplan apply
}

case $1 in
    select) selectinterface;;
    print) printinterfaceinformation $2;;
    version) backuprestore $2 $3;;
    prepare) [ $2 ] && interface=$2 && prepareconfigfile $interface;;
    change) changeconfigfile $2;;
    verify) verifyconfig;;
    *) cat $configfile.edit;;
esac
